language: python
cache: pip

matrix:
  include:
    - python: '2.7'
    - python: '3.5'
    - python: '3.6'

install: pip install -r requirements-dev.txt

script: pytest

deploy:
  provider: pypi
  user: testblogdeploy
  password:
    secure: "LLhCDuE3cBPPjXVSDXg4ye3boh5n0XOZWo2j2C0gT+UFj9g7Yb5GfhhZX8hX7II3jBkUy3wkNWXnfNbVZQp+jeNpxs2vjxyckV5CD+3/gxTsvgVM9LXx5vBB6pLkKCrxvddMUKFBhzwyfb4D5IDk5L20Arbxy2MtFBYz3qD1zuXM/Ks9n8v9kV5atdP04gd+HFx/VH2S39CO9NhJ4091fUvQ7agL888aa5FQ4QU3cXszC97tyKWXRwuMGXmRwT/50XdVJWTeRS01cSUWP7KJyvs7BiRvRb1Un9eXSxoJjkajUcNImTIyD1nydqdzcju2+w/wYR6PC5f1kDXzHpePMpDMeWJxVMMVUEMEk3a2CywnlxSdoglBlLEpv6inN45LxVhxHXLFT+mPd3srTGU3D8xoBWhzSRib8f5mqQyqnj+mSCDw9M00bTHsv0/vXARuOkTkN1Boq7swE85Lq0rwWhwa1ThnxkSy1SwrfSk3w7BM4sXZf7n7hXmJLiW7n/OkCU9qSZ6OYKfEo73z73KruDdX1EDWpTrv2jGPkVtBcsUtsFLrSSK1Twp/P0AsEGW3egV7XIpKzeat94w/Qja1HWyAeTv39ud85jKj4z69hfNzlkXud5gz9pme/mVzLNXGo0r6vYaMJlGhYvuYl+rq4Iw2y6Id6RHjvMXTfT7MYI8="
  distributions: sdist bdist_wheel
  on:
    tags: true
