language: python
cache: pip

matrix:
  include:
    - python: '2.7'
    - python: '3.5'
    - python: '3.6'

install: pip install -r requirements-dev.txt

script: pytest

deploy:
  provider: pypi
  user: testblogdeploy
  password:
    secure: "LBiETlcO3EFqxZLn4Q212GPehH0UZ0QMdUW0n7Bi4frkSC56dk6gbyi6eAVInVM+jMD59uoZfGIatwvgmUO7L4MeHIADr/HkbEsbRSnmwozsa3ZKGf9ix5KHCodIhPpwNvfDnz1EVcOodI1g0E/Ng7nS9w6CElHJjwstH1bnUBtcnwiuvfqDpe4UyYYI26GUJEFMPenJkqtb2u6IjDM/3LhoS9rfj5PamT0+dXaVynangihDuQoBK10z6TPQd/ZrsjJzE5H6y+KDdTueY6OVpDFpzzPCxhb2+OMSyLVXmmxXCKE4p5uzwKXRk2mU/olRgSc/GSqS+aCJig9lfPDb+QWWfPLOUCm8kCWNp82kyykKT7Q4EB34FMW2XaSbsrbScTOwPZJ3gBAG0VfdcwfqFZyt2l6zGMiN9t9+lzpyTkRYyNHD5qWIZ5oH6lUMyK4sysaH3kJi+kg6JCJ78WFPdieX/BSGnCDe49WI2JRSY2PK+F3cH+D3tebpJ4LNhcb60bojdzd1LfTZ4bxKxzuIkBDtLFbkG/3w+CzZVQdFPbQAEefVdsmsgLyybLwYxpEAlZfrdpKQc6w0B06MbMRm2YqIvKZuyi/fMRi9QIc5peKLg9QcJJw7da+kgZiOpGRoyvXJgGmdTmPHd9QHLr+2sg2Wm0XluLRopUCPk9W0aWQ="
  distributions: sdist bdist_wheel
  on:
    tags: true
